<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Area;
use App\Models\City;

class AddAreasCitiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
            $area = Area::create([ 'name' => [ 'ar' => 'منطقة الرياض', 'en' => '' ], 'country_id' => 1, 'is_active'=> 1, ]);
            City::create([ 'name' => [ 'ar' => 'الافلاج', 'en' => 'Aflaj' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999402578', ]);
            City::create([ 'name' => [ 'ar' => 'الخرج', 'en' => 'Kharj' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999739172', ]);
            City::create([ 'name' => [ 'ar' => 'العيينة', 'en' => 'Oyaynah' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999197743', ]);
            City::create([ 'name' => [ 'ar' => 'الغاط', 'en' => 'Alghat' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999685834', ]);
            City::create([ 'name' => [ 'ar' => 'الزلفي', 'en' => 'Zulfi' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999165810', ]);
            City::create([ 'name' => [ 'ar' => 'الدرعية', 'en' => 'DereIyeh' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999416801', ]);
            City::create([ 'name' => [ 'ar' => 'ضرما', 'en' => 'Dhurma' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999572042', ]);
            City::create([ 'name' => [ 'ar' => 'الدلم', 'en' => 'Daelim' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999254278', ]);
            City::create([ 'name' => [ 'ar' => 'حريملاء', 'en' => 'Horaimal' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999676545', ]);
            City::create([ 'name' => [ 'ar' => 'المجمعة', 'en' => 'Majma' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999137719', ]);
            City::create([ 'name' => [ 'ar' => 'رماح', 'en' => 'Remah' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999402117', ]);
            City::create([ 'name' => [ 'ar' => 'الرياض', 'en' => 'Riyadh' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999268602', ]);
            City::create([ 'name' => [ 'ar' => 'صلبوخ', 'en' => 'Salbookh' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999440718', ]);
            City::create([ 'name' => [ 'ar' => 'شقراء', 'en' => 'Shaqra' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999231791', ]);
            City::create([ 'name' => [ 'ar' => 'الدوادمي', 'en' => 'Dawadmi' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999488880', ]);
            City::create([ 'name' => [ 'ar' => 'عفيف', 'en' => 'Afif' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999796521', ]);
            City::create([ 'name' => [ 'ar' => 'الأرطاوية', 'en' => 'Artawiah' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999300275', ]);
            City::create([ 'name' => [ 'ar' => 'الحريق', 'en' => 'Hareeq' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999331841', ]);
            City::create([ 'name' => [ 'ar' => 'المزاحمية', 'en' => 'Muzahmiah' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999249944', ]);
            City::create([ 'name' => [ 'ar' => 'القصب', 'en' => 'Qasab' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999133480', ]);
            City::create([ 'name' => [ 'ar' => 'القويعية', 'en' => 'QuweiIeh' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999968348', ]);
            City::create([ 'name' => [ 'ar' => 'الصحنة', 'en' => 'Sahna' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999874677', ]);
            City::create([ 'name' => [ 'ar' => 'السليل', 'en' => 'Sulaiyl' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999880823', ]);
            City::create([ 'name' => [ 'ar' => 'حوطة بني تميم', 'en' => 'Hawtat Bani Tamim' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999575527', ]);
            City::create([ 'name' => [ 'ar' => 'حوطة سدير', 'en' => 'Hotat Sudair' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999699654', ]);
            City::create([ 'name' => [ 'ar' => 'جلاجل', 'en' => 'Jalajel' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999468149', ]);
            City::create([ 'name' => [ 'ar' => 'مرات', 'en' => 'Mrat' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'999967528', ]);
            City::create([ 'name' => [ 'ar' => 'روضة سدير', 'en' => 'Rowdat Sodair' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999307710', ]);
            City::create([ 'name' => [ 'ar' => 'ساجر', 'en' => 'Sajir' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'999912936', ]);
            City::create([ 'name' => [ 'ar' => 'أم الجماجم', 'en' => 'Um Aljamajim' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999427422', ]);
            City::create([ 'name' => [ 'ar' => 'وادي الدواسر', 'en' => 'Wadi El Dwaser' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999783199', ]);
            City::create([ 'name' => [ 'ar' => 'القويعية', 'en' => 'QuweiIeh' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999456179', ]);
            City::create([ 'name' => [ 'ar' => 'مليح', 'en' => 'Mulayh' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999550487', ]);
            $area = Area::create([ 'name' => [ 'ar' => 'منطقة القصيم', 'en' => '' ], 'country_id' => 1, 'is_active'=> 1, ]);
            City::create([ 'name' => [ 'ar' => 'الدليمية', 'en' => 'Al Dalemya' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999856935', ]);
            City::create([ 'name' => [ 'ar' => 'الرس', 'en' => 'Alrass' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999967439', ]);
            City::create([ 'name' => [ 'ar' => 'عين ابن فهيد', 'en' => 'Ayn Fuhayd' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999688073', ]);
            City::create([ 'name' => [ 'ar' => 'البدائع', 'en' => 'Badaya' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999722996', ]);
            City::create([ 'name' => [ 'ar' => 'البكيرية', 'en' => 'Bukeiriah' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999709082', ]);
            City::create([ 'name' => [ 'ar' => 'بريدة', 'en' => 'Buraidah' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999642740', ]);
            City::create([ 'name' => [ 'ar' => 'عنيزة', 'en' => 'Onaiza' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999354789', ]);
            City::create([ 'name' => [ 'ar' => 'رياض الخبراء', 'en' => 'Riyadh Al Khabra' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999698235', ]);
            City::create([ 'name' => [ 'ar' => 'الاسياح', 'en' => 'Al Asyah' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999342742', ]);
            City::create([ 'name' => [ 'ar' => 'المذنب', 'en' => 'Muzneb' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999983894', ]);
            $area = Area::create([ 'name' => [ 'ar' => 'المنطقة الشرقية', 'en' => '' ], 'country_id' => 1, 'is_active'=> 1, ]);
            City::create([ 'name' => [ 'ar' => 'بقيق', 'en' => 'Abqaiq' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999883039', ]);
            City::create([ 'name' => [ 'ar' => 'عين دار الجديده', 'en' => 'Ain Dar' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999164025', ]);
            City::create([ 'name' => [ 'ar' => 'الخبر', 'en' => 'Khobar' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999363637', ]);
            City::create([ 'name' => [ 'ar' => 'القارة', 'en' => 'Qarah' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999645508', ]);
            City::create([ 'name' => [ 'ar' => 'الأحساء', 'en' => 'Al Hassa' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999124092', ]);
            City::create([ 'name' => [ 'ar' => 'عنك', 'en' => 'Anak' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999153827', ]);
            City::create([ 'name' => [ 'ar' => 'الدمام', 'en' => 'Dammam' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999302359', ]);
            City::create([ 'name' => [ 'ar' => 'الظهران', 'en' => 'Dhahran' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'999987171', ]);
            City::create([ 'name' => [ 'ar' => 'الهفوف', 'en' => 'Hofuf' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999525092', ]);
            City::create([ 'name' => [ 'ar' => 'الجبيل', 'en' => 'Jubail' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999147057', ]);
            City::create([ 'name' => [ 'ar' => 'المبرز', 'en' => 'Mubaraz' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999468849', ]);
            City::create([ 'name' => [ 'ar' => 'العثمانية', 'en' => 'Othmanyah' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999610022', ]);
            City::create([ 'name' => [ 'ar' => 'القطيف', 'en' => 'Qatif' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999519447', ]);
            City::create([ 'name' => [ 'ar' => 'رأس تنورة', 'en' => 'Ras Tanura' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'999987224', ]);
            City::create([ 'name' => [ 'ar' => 'صفوى', 'en' => 'Safwa' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999887992', ]);
            City::create([ 'name' => [ 'ar' => 'سلوى', 'en' => 'Salwa' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999948772', ]);
            City::create([ 'name' => [ 'ar' => 'سيهات', 'en' => 'Seihat' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999543735', ]);
            City::create([ 'name' => [ 'ar' => 'تاروت', 'en' => 'Tarut' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999784619', ]);
            City::create([ 'name' => [ 'ar' => 'العيون', 'en' => 'Uyun' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999318360', ]);
            City::create([ 'name' => [ 'ar' => 'الخفجي', 'en' => 'Khafji' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999318387', ]);
            City::create([ 'name' => [ 'ar' => 'القيصومة', 'en' => 'Qaysoomah' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999138974', ]);
            City::create([ 'name' => [ 'ar' => 'الطرف', 'en' => 'Turaif' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999617564', ]);
            City::create([ 'name' => [ 'ar' => 'النعيرية', 'en' => 'Nanyah' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999578475', ]);
            City::create([ 'name' => [ 'ar' => 'السفانية', 'en' => 'Safanyah' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999836320', ]);
            City::create([ 'name' => [ 'ar' => 'الصرار', 'en' => 'Sarar' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999968681', ]);
            City::create([ 'name' => [ 'ar' => 'البطحاء', 'en' => 'Batha' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999272721', ]);
            City::create([ 'name' => [ 'ar' => 'حفر الباطن', 'en' => 'Hafer Al Batin' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999592419', ]);
            City::create([ 'name' => [ 'ar' => 'حرض', 'en' => 'Harad' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999660939', ]);
            City::create([ 'name' => [ 'ar' => 'الجفر', 'en' => 'Jafar' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999165192', ]);
            City::create([ 'name' => [ 'ar' => 'مليجة', 'en' => 'Mulaija' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999795751', ]);
            City::create([ 'name' => [ 'ar' => 'رأس الخير', 'en' => 'Ras Al Kheir' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999904358', ]);
            City::create([ 'name' => [ 'ar' => 'رأس تنورة', 'en' => 'Ras Tanura' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999649441', ]);
            City::create([ 'name' => [ 'ar' => 'قرية العليا', 'en' => '' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999144144', ]);
            $area = Area::create([ 'name' => [ 'ar' => 'منطقة المدينة المنورة', 'en' => '' ], 'country_id' => 1, 'is_active'=> 1, ]);
            City::create([ 'name' => [ 'ar' => 'الحناكية', 'en' => 'Hinakeya' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999625997', ]);
            City::create([ 'name' => [ 'ar' => 'بدر', 'en' => 'Bader' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999789518', ]);
            City::create([ 'name' => [ 'ar' => 'حريمل', 'en' => 'Horaimal' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999348835', ]);
            City::create([ 'name' => [ 'ar' => 'خيبر', 'en' => 'Khaibar' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999468389', ]);
            City::create([ 'name' => [ 'ar' => 'المدينة المنورة', 'en' => 'Madinah' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999379300', ]);
            City::create([ 'name' => [ 'ar' => 'مهد الذهب', 'en' => 'Mahad Al Dahab' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999262270', ]);
            City::create([ 'name' => [ 'ar' => 'العلا', 'en' => 'Oula' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999854035', ]);
            City::create([ 'name' => [ 'ar' => 'ينبع', 'en' => 'Yanbu' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999621860', ]);
            City::create([ 'name' => [ 'ar' => 'الشقرة', 'en' => 'Shaqra' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999178024', ]);
            City::create([ 'name' => [ 'ar' => 'العيص', 'en' => 'Al Ais' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'999916320', ]);
            $area = Area::create([ 'name' => [ 'ar' => 'منطقة مكة المكرمة', 'en' => '' ], 'country_id' => 1, 'is_active'=> 1, ]);
            City::create([ 'name' => [ 'ar' => 'الهدى', 'en' => 'Alhada' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'999968155', ]);
            City::create([ 'name' => [ 'ar' => 'عسفان', 'en' => 'Asfan' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999879515', ]);
            City::create([ 'name' => [ 'ar' => 'بحرة', 'en' => 'Bahara' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999302907', ]);
            City::create([ 'name' => [ 'ar' => 'ذهبان', 'en' => 'Zahban' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'999983151', ]);
            City::create([ 'name' => [ 'ar' => 'الحوية', 'en' => 'Haweyah' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999990295', ]);
            City::create([ 'name' => [ 'ar' => 'الجعرانة', 'en' => 'JaAraneh' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999118297', ]);
            City::create([ 'name' => [ 'ar' => 'جدة', 'en' => 'Jeddah' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999874392', ]);
            City::create([ 'name' => [ 'ar' => 'الجموم', 'en' => 'Jumum' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999622447', ]);
            City::create([ 'name' => [ 'ar' => 'خليص', 'en' => 'Khulais' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999821014', ]);
            City::create([ 'name' => [ 'ar' => 'مكة المكرمة', 'en' => 'Makkah' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999773747', ]);
            City::create([ 'name' => [ 'ar' => 'مستورة', 'en' => 'Mastura' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999977344', ]);
            City::create([ 'name' => [ 'ar' => 'نمرة', 'en' => 'Nimra' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999953978', ]);
            City::create([ 'name' => [ 'ar' => 'نمران', 'en' => 'Nimra' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999225443', ]);
            City::create([ 'name' => [ 'ar' => 'الطائف', 'en' => 'Taif' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999485775', ]);
            City::create([ 'name' => [ 'ar' => 'ثول', 'en' => 'Towal' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999398321', ]);
            City::create([ 'name' => [ 'ar' => 'تربة', 'en' => 'Turbah' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999996456', ]);
            City::create([ 'name' => [ 'ar' => 'الخرمة', 'en' => 'Khurma' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999375865', ]);
            City::create([ 'name' => [ 'ar' => 'الليث', 'en' => 'Laith' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999319476', ]);
            City::create([ 'name' => [ 'ar' => 'القنفذة', 'en' => 'Qunfudah' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999791478', ]);
            City::create([ 'name' => [ 'ar' => 'رابغ', 'en' => 'Rabigh' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999441631', ]);
            City::create([ 'name' => [ 'ar' => 'رنية', 'en' => 'Rania' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999562985', ]);
            $area = Area::create([ 'name' => [ 'ar' => 'منطقة حائل', 'en' => '' ], 'country_id' => 1, 'is_active'=> 1, ]);
            City::create([ 'name' => [ 'ar' => 'حائل', 'en' => 'Hail' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999803220', ]);
            City::create([ 'name' => [ 'ar' => 'الحائط', 'en' => 'Al hait' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999734178', ]);
            City::create([ 'name' => [ 'ar' => 'بقعاء', 'en' => 'Baqaa' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999955202', ]);
            $area = Area::create([ 'name' => [ 'ar' => 'منطقة الجوف', 'en' => '' ], 'country_id' => 1, 'is_active'=> 1, ]);
            City::create([ 'name' => [ 'ar' => 'دومة الجندل', 'en' => 'Domat Al Jandal' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999717340', ]);
            City::create([ 'name' => [ 'ar' => 'القريات', 'en' => 'Qurayat' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999516995', ]);
            City::create([ 'name' => [ 'ar' => 'سكاكا', 'en' => 'Sakaka' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999120212', ]);
            City::create([ 'name' => [ 'ar' => 'طبرجل', 'en' => 'Tabrjal' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999370547', ]);
            $area = Area::create([ 'name' => [ 'ar' => 'منطقة تبوك', 'en' => '' ], 'country_id' => 1, 'is_active'=> 1, ]);
            City::create([ 'name' => [ 'ar' => 'البدع', 'en' => 'Al Bada' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'999916195', ]);
            City::create([ 'name' => [ 'ar' => 'ضباء', 'en' => 'Duba' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999594563', ]);
            City::create([ 'name' => [ 'ar' => 'حالة عمار', 'en' => 'Halat Ammar' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999343065', ]);
            City::create([ 'name' => [ 'ar' => 'حقل', 'en' => 'Haqil' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999301687', ]);
            City::create([ 'name' => [ 'ar' => 'تبوك', 'en' => 'Tabuk' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999564774', ]);
            City::create([ 'name' => [ 'ar' => 'تيماء', 'en' => 'Tayma' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999601776', ]);
            City::create([ 'name' => [ 'ar' => 'أملج', 'en' => 'Umluj' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'999912383', ]);
            City::create([ 'name' => [ 'ar' => 'الوجه', 'en' => 'Wajeh (Al Wajh)' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999539628', ]);
            City::create([ 'name' => [ 'ar' => 'تيماء', 'en' => 'Tayma' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999555469', ]);
            City::create([ 'name' => [ 'ar' => 'الفارعه', 'en' => 'Wadi Faraah' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999648422', ]);
            $area = Area::create([ 'name' => [ 'ar' => 'منطقة عسير', 'en' => '' ], 'country_id' => 1, 'is_active'=> 1, ]);
            City::create([ 'name' => [ 'ar' => 'أبها', 'en' => 'Abha' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999945652', ]);
            City::create([ 'name' => [ 'ar' => 'أحد رفيدة', 'en' => 'Ahad Rufaidah' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999853463', ]);
            City::create([ 'name' => [ 'ar' => 'المجاردة', 'en' => 'Majarda' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999242369', ]);
            City::create([ 'name' => [ 'ar' => 'بللسمر', 'en' => 'Balasmar' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'999942739', ]);
            City::create([ 'name' => [ 'ar' => 'بارق', 'en' => 'Bareq' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999365249', ]);
            City::create([ 'name' => [ 'ar' => 'بيشة', 'en' => 'Bisha' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999613910', ]);
            City::create([ 'name' => [ 'ar' => 'ظهران الجنوب', 'en' => 'Dhahran Al Janoob' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999173960', ]);
            City::create([ 'name' => [ 'ar' => 'خميس مشيط', 'en' => 'Khamis Mushait' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999667685', ]);
            City::create([ 'name' => [ 'ar' => 'محايل عسير', 'en' => 'Mohayel Aseer' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999407544', ]);
            City::create([ 'name' => [ 'ar' => 'النماص', 'en' => 'Namas' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999911161', ]);
            City::create([ 'name' => [ 'ar' => 'رجال ألمع', 'en' => 'Rejal AlmaA' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999694393', ]);
            City::create([ 'name' => [ 'ar' => 'سبت العلاية', 'en' => 'Sabt El Alaya' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999142626', ]);
            City::create([ 'name' => [ 'ar' => 'سراة عبيدة', 'en' => 'Sarat Obeida' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999666432', ]);
            City::create([ 'name' => [ 'ar' => 'تنومة', 'en' => 'Tanuma' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999424130', ]);
            City::create([ 'name' => [ 'ar' => 'تثليث', 'en' => 'Tatleeth' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999261602', ]);
            City::create([ 'name' => [ 'ar' => 'البرك', 'en' => 'Bareq' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999631111', ]);
            City::create([ 'name' => [ 'ar' => 'الحرجة', 'en' => 'Harajah' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999787879', ]);
            City::create([ 'name' => [ 'ar' => 'القحمة', 'en' => 'Qahmah' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999402188', ]);
            City::create([ 'name' => [ 'ar' => 'الواديين', 'en' => 'Wadeien' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999804319', ]);
            $area = Area::create([ 'name' => [ 'ar' => 'منطقة الحدود الشمالية', 'en' => '' ], 'country_id' => 1, 'is_active'=> 1, ]);
            City::create([ 'name' => [ 'ar' => 'عرعر', 'en' => 'Arar' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999447357', ]);
            City::create([ 'name' => [ 'ar' => 'رفحاء', 'en' => 'Rafha' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999220860', ]);
            City::create([ 'name' => [ 'ar' => 'طريف', 'en' => 'Taif' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999748750', ]);
            $area = Area::create([ 'name' => [ 'ar' => 'منطقة الباحة', 'en' => '' ], 'country_id' => 1, 'is_active'=> 1, ]);
            City::create([ 'name' => [ 'ar' => 'العقيق', 'en' => 'Aqiq' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'999914243', ]);
            City::create([ 'name' => [ 'ar' => 'الباحة', 'en' => 'Baha' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999255651', ]);
            City::create([ 'name' => [ 'ar' => 'بلجرشي', 'en' => 'Biljurashi' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999793633', ]);
            $area = Area::create([ 'name' => [ 'ar' => 'منطقة جازان', 'en' => '' ], 'country_id' => 1, 'is_active'=> 1, ]);
            City::create([ 'name' => [ 'ar' => 'أبو عريش', 'en' => 'Abu Areish' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999732326', ]);
            City::create([ 'name' => [ 'ar' => 'أحد المسارحة', 'en' => 'Ahad Masarha' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999491269', ]);
            City::create([ 'name' => [ 'ar' => 'بيش', 'en' => 'Bish' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999583429', ]);
            City::create([ 'name' => [ 'ar' => 'ضمد', 'en' => 'Damad' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999481068', ]);
            City::create([ 'name' => [ 'ar' => 'الدرب', 'en' => 'Darb' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999179639', ]);
            City::create([ 'name' => [ 'ar' => 'فرسان', 'en' => 'Farasan' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999742001', ]);
            City::create([ 'name' => [ 'ar' => 'جيزان', 'en' => 'Gizan' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999612604', ]);
            City::create([ 'name' => [ 'ar' => 'الكربوس', 'en' => 'Karboos' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999289892', ]);
            City::create([ 'name' => [ 'ar' => 'صبيا', 'en' => 'Sabya' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999443410', ]);
            City::create([ 'name' => [ 'ar' => 'صامطة', 'en' => 'Samtah' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999221718', ]);
            City::create([ 'name' => [ 'ar' => 'العيدابي', 'en' => 'Al Idabi' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999807952', ]);
            City::create([ 'name' => [ 'ar' => 'الدائر', 'en' => 'Addayer' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999225968', ]);
            City::create([ 'name' => [ 'ar' => 'العارضة', 'en' => '' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999140742', ]);
            $area = Area::create([ 'name' => [ 'ar' => 'منطقة نجران', 'en' => '' ], 'country_id' => 1, 'is_active'=> 1, ]);
            City::create([ 'name' => [ 'ar' => 'نجران', 'en' => 'Najran' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999535249', ]);
            City::create([ 'name' => [ 'ar' => 'شرورة', 'en' => 'Sharourah' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999474596', ]);
            City::create([ 'name' => [ 'ar' => 'حبونا', 'en' => 'Hubuna' ], 'area_id' => $area->id, 'is_active'=> 1, 'torod_city_id'=>'', 'spl_id'=>'9999108193', ]);


         
    }
}
