<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Area;
use App\Models\City;
use App\Models\WarehouseCity;
use App\Models\Warehouse;

class UpdateWarehousesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $warehouse = Warehouse::where('name->ar', 'like', 'Test - الرياض')->first();$new_city = City::where('name->ar', 'like', 'الرياض')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'لين هجر الزراعية - الهفوف')->first();$new_city = City::where('name->ar', 'like', 'المبرز')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'أسترا الزراعية - فرع الرياض (شارع سلام)')->first();$new_city = City::where('name->ar', 'like', 'الرياض')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'الياسين الزراعية - الرياض')->first();$new_city = City::where('name->ar', 'like', 'الرياض')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'الياسين الزراعية - الاحساء')->first();$new_city = City::where('name->ar', 'like', 'الهفوف')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'السنديان العربي الزراعية - معرض الرياض')->first();$new_city = City::where('name->ar', 'like', 'الرياض')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'تاج الزراعية - االخرج')->first();$new_city = City::where('name->ar', 'like', 'الخرج')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'تمور زادنا للتجارة - بريدة')->first();$new_city = City::where('name->ar', 'like', 'بريدة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'الآلات والمواد الزراعية - الخرج')->first();$new_city = City::where('name->ar', 'like', 'الخرج')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'بيت التغليف - جدة')->first();$new_city = City::where('name->ar', 'like', 'جدة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'الزنان للزراعة - الرياض')->first();$new_city = City::where('name->ar', 'like', 'الرياض')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'الياسين الزراعية - الدمام')->first();$new_city = City::where('name->ar', 'like', 'الدمام')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'الياسين الزراعية - جدة')->first();$new_city = City::where('name->ar', 'like', 'جدة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'الياسين الزراعية - المدينة المنورة')->first();$new_city = City::where('name->ar', 'like', 'المدينة المنورة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'الياسين الزراعية - بريدة')->first();$new_city = City::where('name->ar', 'like', 'بريدة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'آل منيف للزراعة - الرياض')->first();$new_city = City::where('name->ar', 'like', 'الرياض')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مصنع شركة تمور المحمدية - الخرج')->first();$new_city = City::where('name->ar', 'like', 'الخرج')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مصنع نخيل العالية للتمور - المدينة المنورة')->first();$new_city = City::where('name->ar', 'like', 'المدينة المنورة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مصنع طيبة للتمور - المدينة المنورة')->first();$new_city = City::where('name->ar', 'like', 'المدينة المنورة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'تلدين للحلول البلاستيكية - حائل')->first();$new_city = City::where('name->ar', 'like', 'حائل')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'أسترا الزراعية - فرع الخرج')->first();$new_city = City::where('name->ar', 'like', 'الخرج')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'أسترا الزراعية - فرع بريدة')->first();$new_city = City::where('name->ar', 'like', 'بريدة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'أسترا الزراعية - فرع حائل')->first();$new_city = City::where('name->ar', 'like', 'حائل')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'أسترا الزراعية - فرع المدينة المنورة')->first();$new_city = City::where('name->ar', 'like', 'المدينة المنورة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'الشركة الوطنية للأسمدة - الرياض')->first();$new_city = City::where('name->ar', 'like', 'الرياض')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'المرشد الزراعية - الخرج')->first();$new_city = City::where('name->ar', 'like', 'الخرج')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'المرشد الزراعية - جدة')->first();$new_city = City::where('name->ar', 'like', 'جدة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'المرشد الزراعية - بريدة')->first();$new_city = City::where('name->ar', 'like', 'بريدة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'المرشد الزراعية - حائل')->first();$new_city = City::where('name->ar', 'like', 'حائل')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'المرشد الزراعية- الدمام')->first();$new_city = City::where('name->ar', 'like', 'الدمام')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مصنع كرتون الخليج - العيون')->first();$new_city = City::where('name->ar', 'like', 'العيون')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'سميك البلاستيك للصناعه - حائل - توصيل')->first();$new_city = City::where('name->ar', 'like', 'حائل')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'أسترا الزراعية - (شحن أرامكس)')->first();$new_city = City::where('name->ar', 'like', 'الدمام')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'أسترا الزراعية - فرع وادي الدواسر')->first();$new_city = City::where('name->ar', 'like', 'وادي الدواسر')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'أسترا الزراعية - فرع نجران')->first();$new_city = City::where('name->ar', 'like', 'نجران')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'أسترا الزراعية - فرع خميس مشيط')->first();$new_city = City::where('name->ar', 'like', 'خميس مشيط')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'أسترا الزراعية - فرع الطائف')->first();$new_city = City::where('name->ar', 'like', 'الطائف')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'أسترا الزراعية - فرع تبوك')->first();$new_city = City::where('name->ar', 'like', 'تبوك')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'أسترا الزراعية - فرع ساجر')->first();$new_city = City::where('name->ar', 'like', 'ساجر')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'أسترا الزراعية - فرع الجوف')->first();$new_city = City::where('name->ar', 'like', 'طبرجل')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'أسترا الزراعية - جدة')->first();$new_city = City::where('name->ar', 'like', 'جدة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'تاج الزراعية - حائل')->first();$new_city = City::where('name->ar', 'like', 'حائل')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'تاج الزراعية - الخرج')->first();$new_city = City::where('name->ar', 'like', 'الخرج')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'تاج الزراعية - بريدة')->first();$new_city = City::where('name->ar', 'like', 'بريدة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'أساسيات التنمية للزراعة - بريدة')->first();$new_city = City::where('name->ar', 'like', 'بريدة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'أساسيات التنمية للزراعة - حائل')->first();$new_city = City::where('name->ar', 'like', 'حائل')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'أساسيات التنمية للزراعة - الخرج')->first();$new_city = City::where('name->ar', 'like', 'الخرج')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'سمنان لحلول المياه - الرياض')->first();$new_city = City::where('name->ar', 'like', 'الرياض')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'سنم الجزيرة - الرياض')->first();$new_city = City::where('name->ar', 'like', 'الرياض')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'تاج الزراعية - طبرجل')->first();$new_city = City::where('name->ar', 'like', 'طبرجل')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'المنجم للأغذية - الرياض')->first();$new_city = City::where('name->ar', 'like', 'الرياض')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'المنجم للأغذية - المدينة المنورة')->first();$new_city = City::where('name->ar', 'like', 'المدينة المنورة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'المنجم للأغذية - بريدة')->first();$new_city = City::where('name->ar', 'like', 'بريدة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'المنجم للأغذية - الدمام')->first();$new_city = City::where('name->ar', 'like', 'الدمام')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'المنجم للأغذية - جدة')->first();$new_city = City::where('name->ar', 'like', 'جدة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'المنجم للأغذية - حائل')->first();$new_city = City::where('name->ar', 'like', 'حائل')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مصنع قطاف للاسمدة - الخرج')->first();$new_city = City::where('name->ar', 'like', 'الخرج')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'بستان الياسمين - المدينة المنورة')->first();$new_city = City::where('name->ar', 'like', 'المدينة المنورة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'آل منيف للزراعة - الخرج')->first();$new_city = City::where('name->ar', 'like', 'الخرج')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'ريبال - جدة')->first();$new_city = City::where('name->ar', 'like', 'جدة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'آل منيف للزراعة - حائل')->first();$new_city = City::where('name->ar', 'like', 'حائل')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'آل منيف للزراعة - حرض')->first();$new_city = City::where('name->ar', 'like', 'حرض')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'آل منيف للزراعة - طبرجل')->first();$new_city = City::where('name->ar', 'like', 'طبرجل')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'آل منيف للزراعة - بريدة')->first();$new_city = City::where('name->ar', 'like', 'بريدة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'آل منيف للزراعة - تبوك')->first();$new_city = City::where('name->ar', 'like', 'تبوك')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'آل منيف للزراعة - وادي الدواسر')->first();$new_city = City::where('name->ar', 'like', 'وادي الدواسر')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'آل منيف للزراعة - الأفلاج')->first();$new_city = City::where('name->ar', 'like', 'الافلاج')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'آل منيف للزراعة - الدلم')->first();$new_city = City::where('name->ar', 'like', 'الدلم')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'آل منيف للزراعة - ساجر')->first();$new_city = City::where('name->ar', 'like', 'ساجر')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'الجمعية التعاونية الزراعية - عنيزة - توصيل')->first();$new_city = City::where('name->ar', 'like', 'عنيزة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مصانع الشرق للبلاستيك - الرياض (أحمد الخطيب)')->first();$new_city = City::where('name->ar', 'like', 'الرياض')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'ساره ستار للتجارة - الرياض')->first();$new_city = City::where('name->ar', 'like', 'الرياض')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'الرواد الدولية - الدمام')->first();$new_city = City::where('name->ar', 'like', 'الدمام')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'الرواد الدولية - الرياض')->first();$new_city = City::where('name->ar', 'like', 'الرياض')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مصنع بلاستيك الرياض - الرياض')->first();$new_city = City::where('name->ar', 'like', 'الرياض')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'الرؤيا لصناعة الأسمدة - الرياض')->first();$new_city = City::where('name->ar', 'like', 'الرياض')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'الرؤيا لصناعة الأسمدة - وادي الدواسر')->first();$new_city = City::where('name->ar', 'like', 'وادي الدواسر')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'الرؤيا لصناعة الأسمدة - الخرج')->first();$new_city = City::where('name->ar', 'like', 'الخرج')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'الرؤيا لصناعة الأسمدة - تبوك')->first();$new_city = City::where('name->ar', 'like', 'تبوك')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'وادي الصفوة الزراعية - وادي الدواسر')->first();$new_city = City::where('name->ar', 'like', 'وادي الدواسر')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'شركة الدلتا - الرياض')->first();$new_city = City::where('name->ar', 'like', 'الرياض')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'آل طالب للزراعة والتجارة - الرياض (نصار)')->first();$new_city = City::where('name->ar', 'like', 'الرياض')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'الجمعية التعاونية الزراعية - العلا')->first();$new_city = City::where('name->ar', 'like', 'العلا')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'Test - الأحساء')->first();$new_city = City::where('name->ar', 'like', 'الهفوف')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مؤسسة العطاء الزراعية - الدمام')->first();$new_city = City::where('name->ar', 'like', 'الدمام')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مجموعة عبدالله عبدالمحسن البازعي للتجارة - تبوك')->first();$new_city = City::where('name->ar', 'like', 'تبوك')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'محمد عبدالله الحبلين - بريدة')->first();$new_city = City::where('name->ar', 'like', 'بريدة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مدخلات الزراعة التجارية - الخرج')->first();$new_city = City::where('name->ar', 'like', 'الخرج')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'المدارات السعودية - جدة')->first();$new_city = City::where('name->ar', 'like', 'جدة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مؤسسة نبات المستقبل - مستودع بريدة')->first();$new_city = City::where('name->ar', 'like', 'بريدة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مؤسسة نبات المستقبل - حائل')->first();$new_city = City::where('name->ar', 'like', 'حائل')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مؤسسة نبات المستقبل - طبرجل')->first();$new_city = City::where('name->ar', 'like', 'طبرجل')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مؤسسة نبات المستقبل - بريدة')->first();$new_city = City::where('name->ar', 'like', 'بريدة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'البيرق للمنتجات الكرتونية - المدينة المنورة')->first();$new_city = City::where('name->ar', 'like', 'المدينة المنورة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'أعمال الأندلس للأسمدة - تبوك (هاني عبد العزيز)')->first();$new_city = City::where('name->ar', 'like', 'تبوك')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'أعمال الأندلس للأسمدة - بريدة (ياسر الجيشي)')->first();$new_city = City::where('name->ar', 'like', 'بريدة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'أعمال الأندلس للأسمدة - وادي الدواسر (محمدي إبراهيم)')->first();$new_city = City::where('name->ar', 'like', 'وادي الدواسر')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'أعمال الأندلس للأسمدة - طبرجل (تامر)')->first();$new_city = City::where('name->ar', 'like', 'طبرجل')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'القصيم للكرتون - بريدة (Ahmed Amer)')->first();$new_city = City::where('name->ar', 'like', 'بريدة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'إيراد المتحدة التجارية - الرياض (شارع 18)')->first();$new_city = City::where('name->ar', 'like', 'الرياض')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مصنع ايجيك للكرتون - جدة')->first();$new_city = City::where('name->ar', 'like', 'جدة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'أساس المزرعة - الخرج')->first();$new_city = City::where('name->ar', 'like', 'الخرج')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'الحلول الزراعية - جدة (محمد ثامر)')->first();$new_city = City::where('name->ar', 'like', 'جدة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'الوسائل الصناعية - المدينة المنورة (محمد عطية)')->first();$new_city = City::where('name->ar', 'like', 'المدينة المنورة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'الوسائل الصناعية - الرياض (أحمد حسن) طويق')->first();$new_city = City::where('name->ar', 'like', 'الرياض')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'التكامل الوطنية للزراعة - الرياض (الحائر)')->first();$new_city = City::where('name->ar', 'like', 'الرياض')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'التكامل الوطنية للزراعة - الخرج')->first();$new_city = City::where('name->ar', 'like', 'الخرج')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'التكامل الوطنية للزراعة - الرياض (سلام)')->first();$new_city = City::where('name->ar', 'like', 'الرياض')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'واحة الرياض الخضراء - الرياض')->first();$new_city = City::where('name->ar', 'like', 'الرياض')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'حلول الفلاّح الزراعية - بريدة')->first();$new_city = City::where('name->ar', 'like', 'بريدة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'الوسائل الصناعية - بريدة (عبدالعزيز العجلان)')->first();$new_city = City::where('name->ar', 'like', 'بريدة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'الوسائل الصناعية - الهفوف (أيمن علاء)')->first();$new_city = City::where('name->ar', 'like', 'الهفوف')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'الوسائل الصناعية - عنيزة (حاتم مصطفى)')->first();$new_city = City::where('name->ar', 'like', 'عنيزة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'الوسائل الصناعية - الخرج (أنور عبديل غزالة)')->first();$new_city = City::where('name->ar', 'like', 'الخرج')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'الوسائل الصناعية - جدة (إبراهيم المنشاوي)')->first();$new_city = City::where('name->ar', 'like', 'جدة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'الوسائل الصناعية - الدمام (محمد ربيع)')->first();$new_city = City::where('name->ar', 'like', 'الدمام')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'الوسائل الصناعية - حائل (محمد فضل )')->first();$new_city = City::where('name->ar', 'like', 'حائل')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'بيت التغليف - الرياض')->first();$new_city = City::where('name->ar', 'like', 'الرياض')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'الوسائل الصناعية - العلا (ايمن محروس)')->first();$new_city = City::where('name->ar', 'like', 'العلا')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'الوسائل الصناعية - الزلفي (ناصر العبيد)')->first();$new_city = City::where('name->ar', 'like', 'الزلفي')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'الوسائل الصناعية - وادي الدواسر (عمرو محمد إسماعيل)')->first();$new_city = City::where('name->ar', 'like', 'وادي الدواسر')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'الوسائل الصناعية - جيزان (حسام جودة)')->first();$new_city = City::where('name->ar', 'like', 'صبيا')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'الوسائل الصناعية - تبوك (محمود سامي)')->first();$new_city = City::where('name->ar', 'like', 'تبوك')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'الوسائل الصناعية - نجران (محمد القطان)')->first();$new_city = City::where('name->ar', 'like', 'نجران')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'الوسائل الصناعية - الرياض (موسى) السلام')->first();$new_city = City::where('name->ar', 'like', 'الرياض')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'الوسائل الصناعية - الطائف (أحمد محرم)')->first();$new_city = City::where('name->ar', 'like', 'الطائف')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'سمنان للغطاسات - مستودع الرياض')->first();$new_city = City::where('name->ar', 'like', 'الرياض')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'العرفج الزراعية - الهفوف')->first();$new_city = City::where('name->ar', 'like', 'الهفوف')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'الوسائل الصناعية - خميس مشيط (فارس الحارثي)')->first();$new_city = City::where('name->ar', 'like', 'خميس مشيط')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مؤسسة ومشاتل الأمثل الزراعية - المبرز')->first();$new_city = City::where('name->ar', 'like', 'المبرز')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'الوسائل الصناعية - بريدة المستودع الرئيسي ارامكس توصيل فقط-زيد المطيري0506402491- ابراهيم الكامل0500141394-احمد عباس0506354815')->first();$new_city = City::where('name->ar', 'like', 'بريدة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'الوسائل الصناعية - بريدة (علي عبدالرحيم ) الريان')->first();$new_city = City::where('name->ar', 'like', 'بريدة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'شركة محمد عبدالله آل طالب وشركاه للتجارة والزراعة - فرع الحوطة - استلام')->first();$new_city = City::where('name->ar', 'like', 'حوطة بني تميم')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'حرث الزراعية - بريدة')->first();$new_city = City::where('name->ar', 'like', 'بريدة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مؤسسة الصالح الزراعية - المبرز')->first();$new_city = City::where('name->ar', 'like', 'المبرز')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'استرا الزراعية - فرع الدمام')->first();$new_city = City::where('name->ar', 'like', 'الدمام')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'آل طالب للزراعة والتجارة - القصيم - استلام')->first();$new_city = City::where('name->ar', 'like', 'بريدة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'آل طالب للزراعة والتجارة - الدمام - استلام')->first();$new_city = City::where('name->ar', 'like', 'الدمام')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مؤسسة علاء التجارية - الهفوف')->first();$new_city = City::where('name->ar', 'like', 'الهفوف')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مؤسسة الدخيل التجارية - بريدة')->first();$new_city = City::where('name->ar', 'like', 'بريدة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مؤسسة الدخيل التجارية - حائل')->first();$new_city = City::where('name->ar', 'like', 'حائل')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مستودع الاستلام مؤسسة ومشاتل الامثل الزراعية - المبرز')->first();$new_city = City::where('name->ar', 'like', 'المبرز')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'شركة الماجد الزراعية - تبوك - توصيل')->first();$new_city = City::where('name->ar', 'like', 'تبوك')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'شركة الماجد الزراعية - بئر بن هرماس')->first();$new_city = City::where('name->ar', 'like', 'تبوك')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'الصيادي لوسائل الري للزراعة - المدينة المنورة - توصيل')->first();$new_city = City::where('name->ar', 'like', 'المدينة المنورة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مؤسسة العرفج الزراعية - الهفوف ( استلام )')->first();$new_city = City::where('name->ar', 'like', 'الهفوف')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'شركة مصنع الريف للأسمدة العضوية - ارض المصنع')->first();$new_city = City::where('name->ar', 'like', 'الخرج')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'الجمعية التعاونية بحوطة بني تميم متعددة الأغراض - حوطة بني تميم')->first();$new_city = City::where('name->ar', 'like', 'حوطة بني تميم')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مصنع سميك البلاستيك للصناعه - جده')->first();$new_city = City::where('name->ar', 'like', 'جدة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مصنع سميك البلاستيك للصناعه - حائل')->first();$new_city = City::where('name->ar', 'like', 'حائل')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'شركة جودي الخضراء الزراعيه - الرياض - توصيل')->first();$new_city = City::where('name->ar', 'like', 'الرياض')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'شركة جودي الخضراء الزراعيه - الرياض - استلام')->first();$new_city = City::where('name->ar', 'like', 'الرياض')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'الجمعية التعاونية الزراعية- عنيزة - تسليم')->first();$new_city = City::where('name->ar', 'like', 'عنيزة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'الجمعية التعاونية الزراعية - العلا-استلام')->first();$new_city = City::where('name->ar', 'like', 'العلا')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مؤسسة علاء التجارية - الهفوف - استلام فقط')->first();$new_city = City::where('name->ar', 'like', 'الهفوف')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'الصيادي لوسائل الري للزراعة')->first();$new_city = City::where('name->ar', 'like', 'المدينة المنورة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'شركة الضيف للإستثمار الزراعي - استلام')->first();$new_city = City::where('name->ar', 'like', 'بريدة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مؤسسة سعود بن طالب')->first();$new_city = City::where('name->ar', 'like', 'حوطة بني تميم')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'الجمعية التعاونية الزراعية بالزلفي - توصيل')->first();$new_city = City::where('name->ar', 'like', 'الزلفي')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'الياسين الزراعية - نجران')->first();$new_city = City::where('name->ar', 'like', 'نجران')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'الياسين الزراعية - الخرج')->first();$new_city = City::where('name->ar', 'like', 'الخرج')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'اسامة')->first();$new_city = City::where('name->ar', 'like', 'بريدة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'الجمعية التعاونية بالغاط')->first();$new_city = City::where('name->ar', 'like', 'الغاط')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'سمنان لحلول المياه - بيشة')->first();$new_city = City::where('name->ar', 'like', 'بيشة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'سمنان لحلول المياه - الهفوف')->first();$new_city = City::where('name->ar', 'like', 'الهفوف')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'سمنان لحلول المياه - الطائف')->first();$new_city = City::where('name->ar', 'like', 'الطائف')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'سمنان لحلول المياه - تبوك')->first();$new_city = City::where('name->ar', 'like', 'تبوك')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مستودع تلال النماء يحائل')->first();$new_city = City::where('name->ar', 'like', 'حائل')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'المحل')->first();$new_city = City::where('name->ar', 'like', 'الحريق')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'شركة السبعان للتجارة و المقاولات - الدمام - استلام')->first();$new_city = City::where('name->ar', 'like', 'الدمام')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'الياسين الزراعية - وادي الدواسر')->first();$new_city = City::where('name->ar', 'like', 'وادي الدواسر')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'الياسين الزراعية - تبوك')->first();$new_city = City::where('name->ar', 'like', 'تبوك')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'الياسين الزراعية - ساجر')->first();$new_city = City::where('name->ar', 'like', 'ساجر')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'الياسين الزراعية - حائل')->first();$new_city = City::where('name->ar', 'like', 'حائل')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'الياسين الزراعية - الجوف')->first();$new_city = City::where('name->ar', 'like', 'طبرجل')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'شركة سالم الحميدي وشركاؤه - المستودع الرئيسي - الطائف')->first();$new_city = City::where('name->ar', 'like', 'الطائف')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'شركة سالم الحميدي وشركاؤه - فرع المعدات - الطائف - استلام')->first();$new_city = City::where('name->ar', 'like', 'الطائف')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مستودع مؤسسة الرمانة الزراعية')->first();$new_city = City::where('name->ar', 'like', 'بريدة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مستودع القصير')->first();$new_city = City::where('name->ar', 'like', 'بريدة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'البصيلي للتجهيزات الزراعية')->first();$new_city = City::where('name->ar', 'like', 'جدة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'شركة سالم الحميدي وشركاؤه - الطائف - استلام')->first();$new_city = City::where('name->ar', 'like', 'الطائف')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'شركة الضيف للإستثمار الزراعي - القصيم - توصيل')->first();$new_city = City::where('name->ar', 'like', 'بريدة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'الوسائل الصناعية - مكه (ابوحنيفة)')->first();$new_city = City::where('name->ar', 'like', 'مكة المكرمة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'الوسائل الصناعية - سكاكا (شعبان جلال)')->first();$new_city = City::where('name->ar', 'like', 'سكاكا')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'آل طالب للزراعة والتجارة - الخرج - استلام')->first();$new_city = City::where('name->ar', 'like', 'الخرج')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'البكري الزراعية - الدمام - استلام')->first();$new_city = City::where('name->ar', 'like', 'الدمام')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'البكري الزراعية - الرئيسي - توصيل')->first();$new_city = City::where('name->ar', 'like', 'جدة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مستودع حوطة بني تميم')->first();$new_city = City::where('name->ar', 'like', 'حوطة بني تميم')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'رامي الزغول')->first();$new_city = City::where('name->ar', 'like', 'بريدة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مؤسسة سارة ستار - الرياض - إستلام')->first();$new_city = City::where('name->ar', 'like', 'الرياض')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'الجمعية الزراعية الاحساء')->first();$new_city = City::where('name->ar', 'like', 'المبرز')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'سمنان لحلول المياه - الرياض 2')->first();$new_city = City::where('name->ar', 'like', 'الرياض')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'الشركة المحلية للتجارة والزراعة المحدودة - الرياض - استلام')->first();$new_city = City::where('name->ar', 'like', 'الرياض')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مصنع السهام الثلاثة للبلاستيك - الرياض')->first();$new_city = City::where('name->ar', 'like', 'الرياض')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مؤسسة عبدالله علي ياسين الصالح-استلام فقط')->first();$new_city = City::where('name->ar', 'like', 'المبرز')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مؤسسة الدخيل التجارية - طبرجل - استلام')->first();$new_city = City::where('name->ar', 'like', 'طبرجل')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مؤسسة الدخيل التجارية - وادي الدواسر - استلام')->first();$new_city = City::where('name->ar', 'like', 'وادي الدواسر')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مؤسسة حسين الهاشم - الأحساء - المبرز')->first();$new_city = City::where('name->ar', 'like', 'المبرز')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مؤسسة العسيري للزراعة - بريدة - استلام')->first();$new_city = City::where('name->ar', 'like', 'بريدة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مؤسسة العسيري للزراعة - خميس مشيط - توصيل')->first();$new_city = City::where('name->ar', 'like', 'خميس مشيط')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مؤسسة العسيري للزراعة - الرياض - استلام')->first();$new_city = City::where('name->ar', 'like', 'الرياض')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'شركة الغماس')->first();$new_city = City::where('name->ar', 'like', 'بريدة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'Napco National Co')->first();$new_city = City::where('name->ar', 'like', 'الدمام')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'Mohammed althobaity')->first();$new_city = City::where('name->ar', 'like', 'ينبع')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مستودع - الرياض')->first();$new_city = City::where('name->ar', 'like', 'الرياض')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مؤسسة بدر ناصر العليوي التجاريه')->first();$new_city = City::where('name->ar', 'like', 'المبرز')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مؤسسة ابار الأحساء التجارية - المبرز - استلام')->first();$new_city = City::where('name->ar', 'like', 'المبرز')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مصنع صاف للمنتجات البلاستيكية - الرياض - استلام')->first();$new_city = City::where('name->ar', 'like', 'الرياض')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'صاف للمنتجات البلاستيكية - الرياض - توصيل')->first();$new_city = City::where('name->ar', 'like', 'الرياض')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'شركة المطوع التجارية - الرياض - إستلام')->first();$new_city = City::where('name->ar', 'like', 'الرياض')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'شركة المطوع التجارية - الرياض - توصيل')->first();$new_city = City::where('name->ar', 'like', 'الرياض')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مؤسسة سواقي بيشة - بيشة - استلام')->first();$new_city = City::where('name->ar', 'like', 'بيشة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'شركة النخيل للتجارة - الزلفي - إستلام')->first();$new_city = City::where('name->ar', 'like', 'الزلفي')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'شركة النخيل للتجارة - الدمام - استلام')->first();$new_city = City::where('name->ar', 'like', 'الدمام')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'شركة النخيل للتجارة - بريده - استلام')->first();$new_city = City::where('name->ar', 'like', 'بريدة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'شركة النخيل للتجارة - جده - استلام')->first();$new_city = City::where('name->ar', 'like', 'جدة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'شركة النخيل للتجارة - المدينه - استلام')->first();$new_city = City::where('name->ar', 'like', 'المدينة المنورة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'شركة النخيل للتجارة - حايل - استلام')->first();$new_city = City::where('name->ar', 'like', 'حائل')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'شركة النخيل للتجارة - سكاكا - استلام')->first();$new_city = City::where('name->ar', 'like', 'سكاكا')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'شركة أساسيات التنمية للزراعة و التجارة - وادى الدواسر - استلام')->first();$new_city = City::where('name->ar', 'like', 'وادي الدواسر')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'شركة أساسيات التنمية للزراعة و التجارة - طبرجل - استلام')->first();$new_city = City::where('name->ar', 'like', 'طبرجل')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'شركة أساسيات التنمية للزراعة و التجارة - تبوك - استلام')->first();$new_city = City::where('name->ar', 'like', 'تبوك')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مؤسسة متوكل لمواد البناء - المبرز')->first();$new_city = City::where('name->ar', 'like', 'المبرز')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'شركة سالم الحميدي وشركاؤه - الرياض - استلام')->first();$new_city = City::where('name->ar', 'like', 'الرياض')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مؤسسة مروة الجوف للتجارة - استلام')->first();$new_city = City::where('name->ar', 'like', 'طبرجل')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مؤسسة الصوامع الزراعية - المذنب - استلام')->first();$new_city = City::where('name->ar', 'like', 'المذنب')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مؤسسة مروة الجوف للتجارة - الرئيسي - توصيل')->first();$new_city = City::where('name->ar', 'like', 'طبرجل')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مؤسسة السابق التجارية - بريدة - استلام')->first();$new_city = City::where('name->ar', 'like', 'بريدة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مؤسسة عبدالله طاهر البريه - المبرز - استلام')->first();$new_city = City::where('name->ar', 'like', 'المبرز')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مؤسسة عبدالله طاهر البريه - المبرز - توصيل')->first();$new_city = City::where('name->ar', 'like', 'المبرز')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'شركة مسار التقدم للتجارة - الرياض - استلام')->first();$new_city = City::where('name->ar', 'like', 'الرياض')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مؤسسة أحمد ناصر السلطان التجارية - المبرز - استلام')->first();$new_city = City::where('name->ar', 'like', 'المبرز')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'الجمعية التعاونية الزراعية بالفارعة - الفارعة - استلام')->first();$new_city = City::where('name->ar', 'like', 'الفارعه')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مصنع ينبع للكمياويات - ينبع - توصيل')->first();$new_city = City::where('name->ar', 'like', 'ينبع')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مصنع ثمار الخير للتمور')->first();$new_city = City::where('name->ar', 'like', 'الهفوف')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'أ رمضان جابر')->first();$new_city = City::where('name->ar', 'like', 'الرياض')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'شركة أفياء للمقاولات والتزيين بالنباتات - الهفوف - استلام')->first();$new_city = City::where('name->ar', 'like', 'الهفوف')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مؤسسة المرزم الزراعية - الرياض - توصيل')->first();$new_city = City::where('name->ar', 'like', 'الخرج')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مؤسسة حاتم للتشغيل والصيانة - بيشة - استلام')->first();$new_city = City::where('name->ar', 'like', 'بيشة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'الشركة السعودية للري بالتنقيط المحدودة - الرياض - إستلام')->first();$new_city = City::where('name->ar', 'like', 'الرياض')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'Easternpak LTD')->first();$new_city = City::where('name->ar', 'like', 'الدمام')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'شركة أيوب المتحدة التجارية')->first();$new_city = City::where('name->ar', 'like', 'بريدة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'الشركة السعودية للري بالتنقيط المحدودة - القصيم - إستلام')->first();$new_city = City::where('name->ar', 'like', 'بريدة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'الشركة السعودية للري بالتنقيط المحدودة - الخرج - إستلام')->first();$new_city = City::where('name->ar', 'like', 'الخرج')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'الشركة السعودية للري بالتنقيط المحدودة - تبوك - إستلام')->first();$new_city = City::where('name->ar', 'like', 'تبوك')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مؤسسة محمد عبداللة الحوطي الزراعية (توصيل وإستلام)')->first();$new_city = City::where('name->ar', 'like', 'الهفوف')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'ورشة التحكم الحديث')->first();$new_city = City::where('name->ar', 'like', 'بريدة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مستودع شركة المضخات المتقدمة للتجارة')->first();$new_city = City::where('name->ar', 'like', 'الرياض')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مؤسسة محمد عبداللة الحوطي الزراعية (إستلام فقط)')->first();$new_city = City::where('name->ar', 'like', 'الهفوف')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'شركة أيوب المتحدة التجارية (توصيل)')->first();$new_city = City::where('name->ar', 'like', 'بريدة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'شركة مصنع السمحان للمضخات السعودية المحدودة')->first();$new_city = City::where('name->ar', 'like', 'الرياض')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'جبس زراعي (كبريتات الكالسيوم)')->first();$new_city = City::where('name->ar', 'like', 'ينبع')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مصنع محمد ناصر الفريدي للصناعات البلاستيكيه')->first();$new_city = City::where('name->ar', 'like', 'الخرج')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مستودع أساسيات الوادي الزراعية')->first();$new_city = City::where('name->ar', 'like', 'الهفوف')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'شركة الاقتصاد الافتراضي')->first();$new_city = City::where('name->ar', 'like', 'جدة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'pioneers')->first();$new_city = City::where('name->ar', 'like', 'الرياض')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'شركة فلك لحلول الطاقة الشمسية')->first();$new_city = City::where('name->ar', 'like', 'بريدة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'رأفت جميل')->first();$new_city = City::where('name->ar', 'like', 'الرياض')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'سمنان للغطاسات - مستودع القصيم')->first();$new_city = City::where('name->ar', 'like', 'بريدة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مصنع المؤسسة الوطنية للكبريت الزراعي والصناعي')->first();$new_city = City::where('name->ar', 'like', 'الدمام')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'الجمعية التعاونية الزراعية بالزلفي - استلام')->first();$new_city = City::where('name->ar', 'like', 'الزلفي')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مصنع المراعي للاسمدة')->first();$new_city = City::where('name->ar', 'like', 'الخرج')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'مؤسسة الدماخين الزراعية')->first();$new_city = City::where('name->ar', 'like', 'بريدة')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'آل منيف للزراعة _نجران')->first();$new_city = City::where('name->ar', 'like', 'نجران')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'آل منيف للزراعة_القرية العليا')->first();$new_city = City::where('name->ar', 'like', 'قرية العليا')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}
        $warehouse = Warehouse::where('name->ar', 'like', 'آل منيف للزراعة _الطائف')->first();$new_city = City::where('name->ar', 'like', 'الطائف')->first();if($warehouse && $new_city){WarehouseCity::updateOrCreate( [ 'warehouse_id' => $warehouse->id, 'city_id' => $new_city->id ], [ ] );}

    }
}